### ISSUE TITLE
docs are becoming unwieldy

### ISSUE THREAD

**Issue by sndrs** [guardian/libs#227]
1. move module-level READMEs to JSDOC comments in modules
2. auto-build main readme from JSDOC

**Comment by mxdvl** [comment]
On the subject of auto-building readme files: is it worth having the semi-automated table of contents in the README file? Github offers one out of the box already?

![duplicate table of contents](https://user-images.githubusercontent.com/76776/124141729-a3cc0980-da57-11eb-8660-36f78fb9cf25.png)
